- name: install httpd, php, openssl, mysql, mrtg Redhat servers
  become: yes
  tags: redhat, httpd, php
  ansible.builtin.dnf:
    name:
      - "{{ samba_package_name }}"
      - "{{ nfs_package_name }}"
      - "{{ glusterfs_packing_name }}"
      - "{{ vsftpd_package_name }}"
    state: latest
