- name: install httpd, php, openssl, mysql, mrtg Redhat servers
  become: yes
  tags: redhat, httpd, php
  ansible.builtin.dnf:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
      - "{{ openssl_package_name }}"
      - "{{ mysql_package_name }}"
      - "{{ mrtg_package_name }}"
    state: latest


- name: start httpd (Redhaat)
  tags: apache, redhat, httpd
  service:
    name: "{{ apache_service }}" 
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: install apache and php for Ubuntu servers
  tags: ubuntu, apache2
  apt:
    name:
      - apache2
      - libapache2-mod-phpi
      - openssl
    state: latest
  when: ansible_distribution == "Ubuntu"

 #name: deploy Apache config
 # template:
 #src: httpd.conf.j2
 #  dest: /etc/httpd/conf/httpd.conf
 # notify: restart_httpd



